const postActionTypes = {
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    VIEW_POST_START: 'VIEW_POST_START',
    VIEW_POST_SUCCESS: 'VIEW_POST_SUCCESS',
    VIEW_POST_FAILURE: 'VIEW_POST_FAILURE'
};

export default postActionTypes;
